/*

 GAMEPLAYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\Users\carson\Documents\Repos\CodeBreakerGB\Assets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 256
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __GameplayMap_h_INCLUDE
#define __GameplayMap_h_INCLUDE

#define GameplayMapWidth 20
#define GameplayMapHeight 18
#define GameplayMapBank 0

extern const unsigned char GameplayMap[];

#endif

/* End of GAMEPLAYMAP.H */
