/*

 LOSEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\Users\carson\Documents\Repos\CodeBreakerGB\Assets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __LoseMap_h_INCLUDE
#define __LoseMap_h_INCLUDE

#define LoseMapWidth 20
#define LoseMapHeight 18
#define LoseMapBank 0

extern const unsigned char LoseMap[];

#endif

/* End of LOSEMAP.H */
